# Generated by Django 3.2.8 on 2021-11-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPaint', '0002_auto_20211120_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('userID', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
