# Generated by Django 3.2.8 on 2021-11-22 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyPaint', '0003_canvasimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasimg',
            name='collection',
            field=models.ManyToManyField(blank=True, default=0, related_name='artwork', to=settings.AUTH_USER_MODEL),
        ),
    ]
