# Generated by Django 3.2.8 on 2021-11-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyPaint', '0005_canvasimg_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasimg',
            name='uploaded_by',
        ),
    ]
