# Generated by Django 3.2.8 on 2021-11-23 21:47

from django.db import migrations, models
import pyPaint.storage


class Migration(migrations.Migration):

    dependencies = [
        ('pyPaint', '0007_canvasimg_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasimg',
            name='image',
            field=models.ImageField(max_length=50, storage=pyPaint.storage.OverwriteStorage(), upload_to='images/'),
        ),
    ]
