# Generated by Django 3.2.8 on 2021-11-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPaint', '0008_alter_canvasimg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasimg',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
