# Generated by Django 3.2.8 on 2021-11-23 23:02

from django.db import migrations, models
import pyPaint.storage


class Migration(migrations.Migration):

    dependencies = [
        ('pyPaint', '0009_alter_canvasimg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasimg',
            name='image',
            field=models.ImageField(storage=pyPaint.storage.OverwriteStorage(), upload_to='images/'),
        ),
    ]
